version: '3'
services:
  db: 
    image: postgres:12
    volumes:
      - dbdata:/var/lib/postgresql/data/
    env_file:
      - .env
  
  server:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    command: 'sh -c "pipenv run uvicorn main:app --host 0.0.0.0 --reload"'

volumes:
  dbdata: